language: node_js
cache: npm

env:
  global:
    - GIT_NAME: A1vy
    - GIT_EMAIL: opensource@fiverr.com
    - GITHUB_REPO: fiverr/passable
    - GIT_SOURCE: docs
script:
- echo "skipping tests"

before_script:
- npm run build
- npm run eslint

after_success:
- node ./scripts/prep_docs.js
- chmod +x ./scripts/push_tag_to_master.sh
- if [ "$TRAVIS_BRANCH" = "release" ]; then ./scripts/push_tag_to_master.sh; fi
- chmod +x ./scripts/prepare_next.sh
- if [ "$TRAVIS_BRANCH" != "master" ]; then ./scripts/prepare_next.sh; fi

deploy:
  - provider: npm
    email: evyatar.a@fiverr.com
    skip_cleanup: true
    api_key: $NPM_TOKEN
    on:
      repo: fiverr/passable
      branch: master
  - provider: npm
    email: evyatar.a@fiverr.com
    skip_cleanup: true
    api_key: $NPM_TOKEN
    tag: "next"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = "next"
      repo: fiverr/passable
  - provider: npm
    email: evyatar.a@fiverr.com
    skip_cleanup: true
    api_key: $NPM_TOKEN
    tag: "next-${TRAVIS_COMMIT:(0):6}"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "next" && $TRAVIS_BRANCH != "master" && $TRAVIS_BRANCH != "release"
      repo: fiverr/passable
